//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace OmegaMUD
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class OmegaMUDEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new OmegaMUDEntities object using the connection string found in the 'OmegaMUDEntities' section of the application configuration file.
        /// </summary>
        public OmegaMUDEntities() : base("name=OmegaMUDEntities", "OmegaMUDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OmegaMUDEntities object.
        /// </summary>
        public OmegaMUDEntities(string connectionString) : base(connectionString, "OmegaMUDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new OmegaMUDEntities object.
        /// </summary>
        public OmegaMUDEntities(EntityConnection connection) : base(connection, "OmegaMUDEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Player> Players
        {
            get
            {
                if ((_Players == null))
                {
                    _Players = base.CreateObjectSet<Player>("Players");
                }
                return _Players;
            }
        }
        private ObjectSet<Player> _Players;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Players EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPlayers(Player player)
        {
            base.AddObject("Players", player);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="OmegaMUDModel", Name="Player")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Player : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Player object.
        /// </summary>
        /// <param name="playerName">Initial value of the PlayerName property.</param>
        /// <param name="bBSName">Initial value of the BBSName property.</param>
        public static Player CreatePlayer(global::System.String playerName, global::System.String bBSName)
        {
            Player player = new Player();
            player.PlayerName = playerName;
            player.BBSName = bBSName;
            return player;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String PlayerName
        {
            get
            {
                return _PlayerName;
            }
            set
            {
                if (_PlayerName != value)
                {
                    OnPlayerNameChanging(value);
                    ReportPropertyChanging("PlayerName");
                    _PlayerName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("PlayerName");
                    OnPlayerNameChanged();
                }
            }
        }
        private global::System.String _PlayerName;
        partial void OnPlayerNameChanging(global::System.String value);
        partial void OnPlayerNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String BBSName
        {
            get
            {
                return _BBSName;
            }
            set
            {
                if (_BBSName != value)
                {
                    OnBBSNameChanging(value);
                    ReportPropertyChanging("BBSName");
                    _BBSName = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("BBSName");
                    OnBBSNameChanged();
                }
            }
        }
        private global::System.String _BBSName;
        partial void OnBBSNameChanging(global::System.String value);
        partial void OnBBSNameChanged();

        #endregion
    
    }

    #endregion
    
}
